# Generated by Django 5.2.17 on 2026-10-02 03:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('effective_from', models.DateField()),
                ('source_reference', models.TextField(help_text='Source/version notes; seeds require revalidation.')),
                ('total_duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('maximum_marks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_question_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='exams.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('result_release_at', models.DateTimeField()),
                ('price_paise', models.PositiveIntegerField(default=2900)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION_OPEN', 'Registration Open'), ('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('CLOSED', 'Closed'), ('RESULTS_PUBLISHED', 'Results Published'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('instructions_md', models.TextField(blank=True)),
                ('rules_verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rules_source_notes', models.TextField(blank=True, editable=False)),
                ('exam_scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mocks', to='exams.examscheme')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.examtype')),
                ('rules_verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_mock_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_offset_minutes', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sequence_locked', models.BooleanField(default=False)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='exams.mocktest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('MATHEMATICS', 'Mathematics')], max_length=20)),
                ('question_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('question_type', models.CharField(choices=[('MCQ_SINGLE', 'Single correct MCQ'), ('NUMERICAL', 'Numerical')], max_length=20)),
                ('question_text_md', models.TextField()),
                ('question_image_url', models.URLField(blank=True)),
                ('positive_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('negative_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('correct_numeric_answer', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('numeric_tolerance', models.DecimalField(decimal_places=8, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('explanation_md', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('LOCKED', 'Locked')], default='DRAFT', max_length=10)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='exams.mocktest')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='exams.mockphase')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='AnswerKeyAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_changed', models.CharField(max_length=60)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_key_audit', to='exams.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('option_text_md', models.TextField(blank=True)),
                ('option_image_url', models.URLField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchemePhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_offset_minutes', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sequence_locked', models.BooleanField(default=False, help_text='Lock this phase after its end.')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='exams.examscheme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='mockphase',
            name='scheme_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.schemephase'),
        ),
        migrations.CreateModel(
            name='SchemeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('MATHEMATICS', 'Mathematics')], max_length=20)),
                ('question_type', models.CharField(choices=[('MCQ_SINGLE', 'Single correct MCQ'), ('NUMERICAL', 'Numerical')], max_length=20)),
                ('question_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('positive_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('negative_marks', models.DecimalField(decimal_places=2, help_text='Penalty magnitude: 1 means minus one.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('unanswered_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='exams.schemephase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='examscheme',
            constraint=models.UniqueConstraint(fields=('exam_type', 'version'), name='scheme_exam_version'),
        ),
        migrations.AddConstraint(
            model_name='examscheme',
            constraint=models.CheckConstraint(condition=models.Q(('total_duration_minutes__gt', 0)), name='scheme_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='examscheme',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_marks__gt', 0)), name='scheme_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='examscheme',
            constraint=models.CheckConstraint(condition=models.Q(('total_question_count__gt', 0)), name='scheme_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='mocktest',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='mock_schedule_valid'),
        ),
        migrations.AddConstraint(
            model_name='mocktest',
            constraint=models.CheckConstraint(condition=models.Q(('result_release_at__gte', models.F('ends_at'))), name='mock_release_valid'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('mock_test', 'question_number'), name='mock_question_number'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('negative_marks__gte', 0), ('numeric_tolerance__gte', 0), ('positive_marks__gt', 0), ('question_number__gt', 0)), name='question_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correct_numeric_answer__isnull', False), ('question_type', 'NUMERICAL')), models.Q(('correct_numeric_answer__isnull', True), ('numeric_tolerance', 0), ('question_type', 'MCQ_SINGLE')), _connector='OR'), name='question_answer_shape'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'label'), name='option_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='option_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='schemephase',
            constraint=models.UniqueConstraint(fields=('scheme', 'order'), name='scheme_phase_order'),
        ),
        migrations.AddConstraint(
            model_name='schemephase',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='scheme_phase_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='schemephase',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='scheme_phase_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='mockphase',
            constraint=models.UniqueConstraint(fields=('mock_test', 'order'), name='mock_phase_order'),
        ),
        migrations.AddConstraint(
            model_name='schemerule',
            constraint=models.UniqueConstraint(fields=('phase', 'subject', 'question_type'), name='scheme_rule_unique'),
        ),
        migrations.AddConstraint(
            model_name='schemerule',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__gt', 0)), name='rule_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='schemerule',
            constraint=models.CheckConstraint(condition=models.Q(('negative_marks__gte', 0), ('positive_marks__gt', 0), ('unanswered_marks', 0)), name='rule_marks_valid'),
        ),
    ]
