# Generated by Django 5.2.17 on 2026-10-02 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('offer_type', models.CharField(choices=[('JEE', 'JEE Main'), ('CET', 'MHT-CET PCM'), ('COMBO', 'JEE + CET')], max_length=5)),
                ('price_paise', models.PositiveIntegerField(blank=True, help_text='Leave blank for initial pricing: JEE/CET 2900, combo 5000 paise.')),
                ('active', models.BooleanField(default=False)),
                ('sales_start_at', models.DateTimeField()),
                ('sales_end_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price_paise__gt', 0)), name='offer_price_positive'), models.CheckConstraint(condition=models.Q(('offer_type__in', ['JEE', 'CET', 'COMBO'])), name='offer_type_valid'), models.CheckConstraint(condition=models.Q(('sales_end_at__gt', models.F('sales_start_at'))), name='offer_sales_window')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_name_snapshot', models.CharField(max_length=160)),
                ('offer_slug_snapshot', models.SlugField()),
                ('offer_type_snapshot', models.CharField(choices=[('JEE', 'JEE Main'), ('CET', 'MHT-CET PCM'), ('COMBO', 'JEE + CET')], max_length=5)),
                ('total_amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', editable=False, max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=8)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('review_required', models.BooleanField(default=False)),
                ('review_note', models.CharField(blank=True, max_length=250)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reference', models.CharField(blank=True, max_length=100)),
                ('refund_reason', models.CharField(blank=True, max_length=40)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerce.mockoffer')),
                ('refund_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_refunds', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_paise_snapshot', models.PositiveIntegerField()),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='exams.mocktest')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='commerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='MockAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('REFUNDED', 'Refunded')], default='ACTIVE', max_length=8)),
                ('granted_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_note', models.CharField(blank=True, max_length=250)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='exams.mocktest')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_grants', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_access', to=settings.AUTH_USER_MODEL)),
                ('source_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='commerce.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(default='RAZORPAY', editable=False, max_length=8)),
                ('gateway_payment_id', models.CharField(max_length=100, unique=True)),
                ('gateway_signature', models.CharField(blank=True, max_length=64)),
                ('amount_paise', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], max_length=10)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_event_id', models.CharField(max_length=150, unique=True)),
                ('event_type', models.CharField(max_length=60)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PROCESSED', 'Processed'), ('IGNORED', 'Ignored')], default='PROCESSED', max_length=10)),
                ('payload_hash', models.CharField(max_length=64)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('processing_status__in', ['PROCESSED', 'IGNORED'])), name='webhook_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='MockOfferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_items', to='exams.mocktest')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='commerce.mockoffer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offer', 'mock_test'), name='offer_mock_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['student', 'offer', 'created_at'], name='commerce_or_student_5551c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_paise__gt', 0)), name='order_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'INR')), name='order_currency_inr'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CREATED', 'PENDING', 'PAID', 'FAILED', 'REFUNDED'])), name='order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'mock_test'), name='order_mock_unique'),
        ),
        migrations.AddConstraint(
            model_name='mockaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'mock_test'), name='one_active_mock_access'),
        ),
        migrations.AddConstraint(
            model_name='mockaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'REVOKED', 'REFUNDED'])), name='access_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('gateway', 'RAZORPAY')), name='payment_gateway_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED'])), name='payment_status_valid'),
        ),
    ]
