# Generated by Django 5.2.17 on 2026-10-03 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted'), ('INVALID', 'Invalid')], default='IN_PROGRESS', max_length=14)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='exams.mocktest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_answer', models.CharField(blank=True, default='', max_length=32)),
                ('marked_for_review', models.BooleanField(default=False)),
                ('first_visited_at', models.DateTimeField()),
                ('mutation_version', models.PositiveBigIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_responses', to='exams.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.questionoption')),
            ],
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status', 'mock_test'], name='attempts_at_status_f02f89_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('student', 'mock_test'), name='one_attempt_per_mock'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['IN_PROGRESS', 'SUBMITTED', 'AUTO_SUBMITTED', 'INVALID'])), name='attempt_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'IN_PROGRESS'), ('submitted_at__isnull', True)), models.Q(('status__in', ['SUBMITTED', 'AUTO_SUBMITTED', 'INVALID']), ('submitted_at__isnull', False)), _connector='OR'), name='attempt_terminal_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='studentresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='one_response_per_question'),
        ),
        migrations.AddConstraint(
            model_name='studentresponse',
            constraint=models.CheckConstraint(condition=models.Q(('mutation_version__gte', 1), ('mutation_version__lte', 9007199254740991)), name='response_version_safe_integer'),
        ),
        migrations.AddConstraint(
            model_name='studentresponse',
            constraint=models.CheckConstraint(condition=models.Q(('selected_option__isnull', True), ('numeric_answer', ''), _connector='OR'), name='response_single_answer_kind'),
        ),
    ]
